# Let's follow pnpm default settings for minimumReleaseAge as sv users will have this by default too.
minimumReleaseAge: 1440
# This Exclude list is for "sv-utils" that we trust & bundle.
# But keep in mind that sv users may not have any exclude list!
minimumReleaseAgeExclude:
  - '@sveltejs/*'
  - svelte
  - esrap
  - devalue
  - zimmerframe
  - prettier-plugin-svelte
  - svelte-check
  - esm-env
blockExoticSubdeps: true

packages:
  - 'packages/*'
  - '!.test-tmp/**'
  - '!**/.test-output/**'

onlyBuiltDependencies:
  - esbuild
